// Reusable framework bundling helpers.
// Extracted from bundle-framework.ts so the same code path serves the monorepo
// today and the external `flowai-cli` repo after the split.
// implements [FR-DIST.BUNDLE](../../documents/requirements.md#fr-dist.bundle-bundled-source)
// implements [FR-DIST.BUNDLE.PIN](../../documents/requirements.md#fr-dist.bundle.pin-pinned-tarball-bundle-source-post-split)
import { walk } from "@std/fs/walk";
import { relative } from "@std/path";

/** Walk srcDir, skip dev-only files, write sorted JSON bundle. Returns file count. */
export async function bundleFrameworkDir(
  srcDir: string,
  outBundlePath: string,
): Promise<number> {
  const bundle: Record<string, string> = {};
  for await (
    const entry of walk(srcDir, { includeFiles: true, includeDirs: false })
  ) {
    const rel = `framework/${relative(srcDir, entry.path)}`;
    if (/\/acceptance-tests\//.test(rel) || /_test\.\w+$/.test(rel)) continue;
    bundle[rel] = await Deno.readTextFile(entry.path);
  }
  const sorted = Object.fromEntries(
    Object.entries(bundle).sort(([a], [b]) => a.localeCompare(b)),
  );
  await Deno.writeTextFile(
    outBundlePath,
    JSON.stringify(sorted, null, 2) + "\n",
  );
  return Object.keys(sorted).length;
}

/** Emit the generated VERSION constant file consumed by cli/src/main.ts. */
export async function writeVersionFile(
  version: string,
  outPath: string,
): Promise<void> {
  const body =
    `// Generated by cli/scripts/bundle-framework.ts — do not edit\nexport const VERSION = "${version}";\n`;
  await Deno.writeTextFile(outPath, body);
}
