// [FR-DIST.BUNDLE](../../documents/requirements.md#fr-dist.bundle-bundled-source) — bundle framework into bundled.json
// [FR-PACKS.BUNDLE](../../documents/requirements.md#fr-packs.bundle-bundle-update) — scan framework/*/ pack structure
/** Bundle framework/ into cli/src/bundled.json + generate cli/src/_version.ts */
import { walk } from "@std/fs/walk";
import { relative } from "@std/path";

const ROOT_DIR = new URL("../../", import.meta.url).pathname;
const FRAMEWORK_DIR = `${ROOT_DIR}framework`;
const OUTPUT_BUNDLE = new URL("../src/bundled.json", import.meta.url).pathname;
const OUTPUT_VERSION = new URL("../src/_version.ts", import.meta.url).pathname;

// 1. Read version from root deno.json
const denoJsonPath = `${ROOT_DIR}deno.json`;
const denoConfig = JSON.parse(await Deno.readTextFile(denoJsonPath));
const version: string = denoConfig.version;

// 2. Bundle framework files
const bundle: Record<string, string> = {};

for await (
  const entry of walk(FRAMEWORK_DIR, { includeFiles: true, includeDirs: false })
) {
  const rel = `framework/${relative(FRAMEWORK_DIR, entry.path)}`;
  // Skip dev-only files (acceptance-tests, tests) — not distributed to users
  if (/\/acceptance-tests\//.test(rel) || /_test\.\w+$/.test(rel)) continue;
  bundle[rel] = await Deno.readTextFile(entry.path);
}

const sorted = Object.fromEntries(
  Object.entries(bundle).sort(([a], [b]) => a.localeCompare(b)),
);

await Deno.writeTextFile(OUTPUT_BUNDLE, JSON.stringify(sorted, null, 2) + "\n");
console.log(
  `Bundled ${Object.keys(sorted).length} files → cli/src/bundled.json`,
);

// 3. Generate version file
const versionContent =
  `// Generated by cli/scripts/bundle-framework.ts — do not edit\nexport const VERSION = "${version}";\n`;
await Deno.writeTextFile(OUTPUT_VERSION, versionContent);
console.log(`Generated cli/src/_version.ts (${version})`);
